---
abstract: 'Net::Leankit is a perl library for Leankit.com'
author:
  - 'Adam Stokes <adamjs@cpan.org>'
build_requires:
  Mojolicious: '0'
  Test::Mojo: '0'
  Test::More: '0'
  Test::NoTabs: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-Leankit
requires:
  Carp: '0'
  Class::Tiny: '0'
  HTTP::Tiny: '0'
  JSON::Any: '0'
  strict: '0'
  warnings: '0'
resources:
  repository: git://github.com/battlemidget/p5-leankit.git
version: '0.001'
